files:
  # Main translation files
  - source: /languages/source/*.*
    translation: /languages/%two_letters_code%/%original_file_name%

  # Email templates (Twig)
  - source: /languages/source/email_templates/*.twig
    translation: /languages/%two_letters_code%/email_templates/%original_file_name%
    type: 'html'

  # HTML templates
  - source: /languages/source/html/*.*
    translation: /languages/%two_letters_code%/html/%original_file_name%
